deployment:
  replicas: 1

ingressRoute:
  dashboard:
    enabled: true
  ingress:
    hosts:
      - host: traefik.local
        paths:
          - "/"

certificatesResolvers:
  letsencrypt:
    acme:
      email: ju.rockmann@gmail.com
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web
