apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:juergenrockmann/meilisearch.git'
    path: infra-helm-argo/apps/traefik
    helm:
      chart: traefik
      repoURL: https://helm.traefik.io/traefik
      targetRevision: 39.0.0
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
